[loggers]
keys=root,main

[logger_root]
level=DEBUG
handlers=console,file

[logger_main]
level=DEBUG
handlers=
propagate=1
qualname=__main__

[handlers]
keys=console,file

[handler_console]
class=StreamHandler
level=DEBUG
formatter=console
args=(sys.stdout,)

[handler_file]
class=FileHandler
level=DEBUG
formatter=file
args=("%(filename)s",)

[formatters]
keys=file,console

[formatter_file]
class=logging.Formatter
format=%(asctime)s %(message)s
datefmt=%H:%M:%S

[formatter_console]
class=logging.Formatter
format=%(asctime)s %(message)s
datefmt=%H:%M:%S
